config/routes.rb
GreenLockers::Application.routes.draw do
  root :to => "pages#index"
  post "api/DoorOpened(.:format)" => "api#DoorOpened"
  post "api/DropOff(.:format)"
  post "api/SyncAccessInfo(.:format)"
  post "api/SyncOperatorInfo(.:format)"
  post "api/SyncAdminInfo(.:format)"
  post "api/BarcodeNotExist(.:format)"
  post "api/BoxIntruded(.:format)"
  
  post "boxes/assign"
  post "boxes/assign_backup"
  post "boxes/reassign"
  post "boxes/reassign_backup"
  post "boxes/delivered"
  post "boxes/picked_up"
  post "boxes/dropped_off"
  post "boxes/received"
  post "boxes/:id/open", to: "boxes#open", as: "open_box"
  
  post "lockers/:id/sync", to: "lockers#sync", as: "sync_locker"
  
  post "employees/set_permissions"
  post "employees/set_privileges"
  
  resources :lockers

  resources :employees

  resources :trackings

  resources :packages

  resources :branches

  resources :boxes

  resources :users
  
  get "logs" => "loggings#index"
  get "logs/box/:id", to: "loggings#box_logs", as: "box_logs"
  get "logs/package/:id", to: "loggings#package_logs", as: "package_logs"
  get "packages/:id/get_available_boxes" => "packages#get_available_boxes"

  

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :boxes, :through => :lockers
  has_many :lockers
  has_many :trackings
  has_many :packages, :foreign_key => 'preferred_branch_id', :class_name => 'Package'
  has_many :users, :foreign_key => 'preferred_branch_id', :class_name => 'User'
  belongs_to :state
  
  def full_name
    return self.name + ', ' + self.city + ', ' + self.state.abbr
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: [:show, :edit, :update, :destroy]
  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render action: 'show', status: :created, location: @branch }
      else
        format.html { render action: 'new' }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:name, :st_address, :apt_address, :city, :state_id, :zip)
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= form_for(@branch) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
      <% @branch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='row'>
    <div class='col-md-4'>
	  <div class="field">
	    <%= f.label :name %><br>
	    <%= f.text_field :name , {:class=>'form-control'} %>
	  </div>
	  <div class="field">
	    <%= f.label :st_address %><br>
	    <%= f.text_field :st_address , {:class=>'form-control'} %>
	  </div>
	  <div class="field">
	    <%= f.label :apt_address %><br>
	    <%= f.text_field :apt_address , {:class=>'form-control'} %>
	  </div>
	  <div class="field">
	    <%= f.label :city %><br>
	    <%= f.text_field :city , {:class=>'form-control'} %>
	  </div>
	  <div class="field">
	    <%= f.label :state_id %><br>
	    <%= f.collection_select :state_id, State.order(:id),:id,:name ,{:include_blank => 'Select State'}, {:class=>'form-control'} %>
	  </div>
	  <div class="field">
	    <%= f.label :zip %><br>
	    <%= f.text_field :zip , {:class=>'form-control'} %>
	  </div>
    </div>
  </div>
  <div class='row'>
  	<div class='col-md-12'>
  	<%= link_to 'Back', branches_path, :class=>"btn btn-default" %>
    <%= f.submit  :class=>'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h4>Edit Branch</h4>

<%= render 'form' %>

app/views/branches/index.html.erb
<h4>Branches</h4>

<%= link_to '+ New Branch', new_branch_path %>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>Name</th>
      <th>St address</th>
      <th>Apt address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @branches.each do |branch| %>
      <tr>
        <td><%= branch.name %></td>
        <td><%= branch.st_address %></td>
        <td><%= branch.apt_address %></td>
        <td><%= branch.city %></td>
        <td><%= branch.state.name %></td>
        <td><%= branch.zip %></td>
        <td><%= link_to 'Show', branch %></td>
        <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
        <td><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/branches/new.html.erb
<h4>New Branch</h4>

<%= render 'form' %>

app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @branch.name %>
</p>

<p>
  <strong>St address:</strong>
  <%= @branch.st_address %>
</p>

<p>
  <strong>Apt address:</strong>
  <%= @branch.apt_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @branch.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @branch.state_id %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @branch.zip %>
</p>

<%= link_to 'Edit', edit_branch_path(@branch) %> |
<%= link_to 'Back', branches_path %>