config/routes.rb
GreenLockers::Application.routes.draw do
  root :to => "pages#index"
  post "api/DoorOpened(.:format)" => "api#DoorOpened"
  post "api/DropOff(.:format)"
  post "api/SyncAccessInfo(.:format)"
  post "api/SyncOperatorInfo(.:format)"
  post "api/SyncAdminInfo(.:format)"
  post "api/BarcodeNotExist(.:format)"
  post "api/BoxIntruded(.:format)"
  
  post "boxes/assign"
  post "boxes/assign_backup"
  post "boxes/reassign"
  post "boxes/reassign_backup"
  post "boxes/delivered"
  post "boxes/picked_up"
  post "boxes/dropped_off"
  post "boxes/received"
  post "boxes/:id/open", to: "boxes#open", as: "open_box"
  
  post "lockers/:id/sync", to: "lockers#sync", as: "sync_locker"
  
  post "employees/set_permissions"
  post "employees/set_privileges"
  
  resources :lockers

  resources :employees

  resources :trackings

  resources :packages

  resources :branches

  resources :boxes

  resources :users
  
  get "logs" => "loggings#index"
  get "logs/box/:id", to: "loggings#box_logs", as: "box_logs"
  get "logs/package/:id", to: "loggings#package_logs", as: "package_logs"
  get "packages/:id/get_available_boxes" => "packages#get_available_boxes"

  

end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy, :assign, :assign_backup, :reassign, :reassign_backup, :delivered, :picked_up, :dropped_off, :received, :open]
  # GET /lockers
  # GET /lockers.json
  def index
    @boxes = Box.all
  end

  # GET /lockers/1
  # GET /lockers/1.json
  def show
    u_packages = Package.where("box_id is NULL and (status = 0 OR status = 5) and status IS NOT NULL").order('updated_at ASC')
    @unassigned_packages = u_packages.select{ |p| 
        if p.preferred_branch_id
          p.preferred_branch_id == @box.branch.id
        elsif p.user.preferred_branch_id
          p.user.preferred_branch_id == @box.branch.id
        else
          true == false
        end 
      }
    @unassigned_packages_for_delivery = @unassigned_packages.select{|p| p.status == '0' }
    @selected_backup_package = @box.backup_package
  end
  
  def open
    respond_to do |format|
      if @box.remote_open
        format.html { redirect_to @box, notice: 'Box is remotely opened.' }
      else
        format.html { redirect_to @box, alert: 'Oops. Something went wrong. Action is not performed.' }
      end
    end
  end

  # GET /lockers/new
  def new
    @box = Box.new
  end

  # GET /lockers/1/edit
  def edit
  end

  # POST /lockers
  # POST /lockers.json
  def create
    @box = Box.new(box_params)

    respond_to do |format|
      if @box.save
        format.html { redirect_to boxes_path, notice: 'Box was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /lockers/1
  # PATCH/PUT /lockers/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to :back, notice: 'Locker was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /lockers/1
  # DELETE /lockers/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url }
    end
  end
  
  def assign
    respond_to do |format|
      return false if params[:package_id].nil?
      if params[:package_id] == '' and @box.deliver_package nil
        format.html { redirect_to :back, notice: 'Package assignment was successfully cancelled.' }
      else
        package = Package.find params[:package_id]
        if package.status != @constant['PACKAGE_WAITING_FOR_DELIVERY'].to_i and package.status != @constant['PACKAGE_WAITING_FOR_DROP_OFF'].to_i
          format.html { redirect_to :back, alert: 'Package assign error. Package is already assigned.' }
        elsif @box.package
          format.html { redirect_to :back, alert: 'Package assign error. Box is already occupied' }
        elsif ( (package.status == @constant['PACKAGE_WAITING_FOR_DROP_OFF'].to_i) ? (@box.drop_off_package params[:package_id]) : (@box.deliver_package params[:package_id]) )
          format.html { redirect_to :back, notice: 'Package was successfully assigned.' }
        else
          format.html { redirect_to :back, alert: 'Package assign error.' }
        end
      end
    end
  end
  
  def assign_backup
    respond_to do |format|
      return false if params[:package_id].nil?
      if params[:package_id] == '' and @box.assign_backup_package nil
        format.html { redirect_to :back, notice: 'Package assignment was successfully cancelled.' }
      else
        package = Package.find params[:package_id]
        if package.status != @constant['PACKAGE_WAITING_FOR_DELIVERY'].to_i
          format.html { redirect_to :back, alert: 'Package assign error. Package is not assignable.' }
        elsif @box.backup_package
          format.html { redirect_to :back, alert: 'Package assign error. Box\'s backup queue is already occupied' }
        elsif @box.assign_backup_package params[:package_id]
          format.html { redirect_to :back, notice: 'Package was successfully assigned.' }
        else
          format.html { redirect_to :back, alert: 'Package assign error.' }
        end
      end
    end
  end

  def reassign
    # reassign a package to a new box
    respond_to do |format|
      return false if params[:package_id].nil?
      if params[:package_id] == ''
        format.html { redirect_to :back, alert: 'Package assign error. No package selected.' }
      else
        package = Package.find params[:package_id]
        if package.status != @constant['PACKAGE_ENROUTE_DELIVERY'].to_i and package.status != @constant['PACKAGE_ENROUTE_DROP_OFF'].to_i and package.status != @constant['PACKAGE_QUEUING_DELIVERY'].to_i
          format.html { redirect_to :back, alert: 'Package assign error. Invalid package status.' }
        elsif @box.package
          format.html { redirect_to :back, alert: 'Package assign error. Box is already occupied' }
        elsif ( (package.status == @constant['PACKAGE_ENROUTE_DROP_OFF'].to_i) ? (@box.drop_off_package params[:package_id]) : (@box.deliver_package params[:package_id]) )
          format.html { redirect_to :back, notice: 'Package was successfully reassigned.' }
        else
          format.html { redirect_to :back, alert: 'Package assign error.' }
        end
      end
    end
  end
  
  def reassign_backup
    respond_to do |format|
      return false if params[:package_id].nil?
      if params[:package_id] == ''
        format.html { redirect_to :back, notice: 'Package assign error. No package selected.' }
      else
        package = Package.find params[:package_id]
        if package.status != @constant['PACKAGE_ENROUTE_DELIVERY'].to_i and package.status !=  @constant['PACKAGE_QUEUING_DELIVERY'].to_i 
          format.html { redirect_to :back, alert: 'Package assign error. Invalid package status.' }
        elsif @box.backup_package
          format.html { redirect_to :back, alert: 'Package assign error. Box\'s backup queue is already occupied' }
        elsif @box.assign_backup_package params[:package_id]
          format.html { redirect_to :back, notice: 'Package was successfully reassigned.' }
        else
          format.html { redirect_to :back, alert: 'Package assign error.' }
        end
      end
    end
  end
  
  def delivered
    respond_to do |format|
      if @box.package_delivered
        Logging.log_manual_action @box, @box.package
        format.html { redirect_to :back, notice: 'Package was successfully delivered.' }
      else
        format.html { redirect_to :back, notice: 'Package deliver error.' }
      end
    end
  end
  
  def picked_up
    respond_to do |format|
      package = @box.package
      if @box.package_picked_up
        Logging.log_manual_action @box, package
        format.html { redirect_to :back, notice: 'Package was successfully picked up.' }
      else
        format.html { redirect_to :back, notice: 'Package pick up error.' }
      end
    end
  end
  
  def dropped_off
    respond_to do |format|
      if @box.package_dropped_off
        Logging.log_manual_action @box, @box.package
        format.html { redirect_to :back, notice: 'Package was successfully dropped off.' }
      else
        format.html { redirect_to :back, notice: 'Package drop off error.' }
      end
    end
  end
  
  def received
    respond_to do |format|
      package = @box.package
      if @box.drop_off_package_received
         Logging.log_manual_action @box, package
        format.html { redirect_to :back, notice: 'DropOff package was successfully received.' }
      else
        format.html { redirect_to :back, notice: 'DropOff package was not received.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:locker_id, :name, :size, :status)
    end
end

app/views/boxes/_form.html.erb
<%= form_for(@box) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this locker from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :locker_id %><br>
    <%= f.collection_select :locker_id, Locker.order(:branch_id),:id,:name, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :size %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boxes/edit.html.erb
<h1>Editing Box</h1>

<%= render 'form' %>

<%= link_to 'Show', @box %> |
<%= link_to 'Back', boxes_path %>

app/views/boxes/index.html.erb
<h1>Listing boxes</h1>

<table>
  <thead>
    <tr>
      <th>Branch</th>
      <th>Locker</th>
      <th>Name</th>
      <th>Size</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @boxes.each do |box| %>
      <tr>
        <td><%= box.branch.name %></td>
        <td><%= box.locker.name %></td>
        <td><%= box.name %></td>
        <td><%= box.print_size %></td>
        <td><%= box.print_status %></td>
        <td><%= link_to 'Manage', box %></td>
        <td><%= link_to 'Edit', edit_box_path(box) %></td>
        <td><%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Box', new_box_path %>

app/views/boxes/new.html.erb
<h1>New box</h1>

<%= render 'form' %>

<%= link_to 'Back', boxes_path %>

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Branch:</strong>
  <%= @box.branch.name %>
</p>

<p>
  <strong>Locker:</strong>
  <%= @box.locker.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @box.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @box.print_size %>
</p>

<p>
  <strong>Status:</strong>
  <%= @box.print_status %>
</p>

<p>
  <strong>Current Assigned Package:</strong>
  ID: <%= @box.package.id if @box.package %> | 
  Barcode: <%= @box.package.barcode if @box.package %>
  <br />
 
  <% if @box.status == @constant['BOX_DELIVERING'] %>
  	<%= form_tag("delivered", method: "post") do %>
  	  <%= submit_tag 'Delivered'%>
  	  <%= hidden_field_tag :id, @box.id %>
  	<% end %>
  <% end %>
  
  <% if @box.status == @constant['BOX_DELIVERED'] %>
  	<%= form_tag("picked_up", method: "post") do %>
  	  <%= submit_tag 'Picked Up'%>
  	  <%= hidden_field_tag :id, @box.id %>
  	<% end %>
  <% end %>
  
  <% if @box.status == @constant['BOX_RETURNING'] %>
    <%= form_tag("dropped_off", method: "post") do %>
      <%= submit_tag 'Dropped off' %>
      <%= hidden_field_tag :id, @box.id %>
    <% end %>
  <% end %>
  
  <% if @box.status == @constant['BOX_RETURNED'] %>
  	<%= form_tag("received", method: "post") do %>
  	  <%= submit_tag 'Received'%>
  	  <%= hidden_field_tag :id, @box.id %>
  	<% end %>
  <% end %>
  
  <% if (@box.package.nil? and @box.status == @constant['BOX_IDLE']) or @box.status == @constant['BOX_DELIVERING'] or @box.status == @constant['BOX_RETURNING'] %>
  	<% if (@box.package.nil? and @box.status == @constant['BOX_IDLE']) %>
  	  Assign Package: 
  	<% else %>
  	  Reassign Package:
  	<% end %>
  	<%= form_tag("assign", method: "post") do %>
  	  <%= select '', :package_id, @unassigned_packages.collect{|p|
	  	  	print_info = p.barcode
	  	  	if p.status == '5'
	  	  	  print_info = print_info + '(DropOff)'
	  	  	end
	  	  	[print_info, p.id]
  	      }, include_blank: 'No/Cancel Assignment' %>
  	  <%= submit_tag 'Assign' %>
  	  <%= hidden_field_tag :id, @box.id %>
  	<% end %>
  <% end %>
  
</p>

<p>
  <strong>Access:</strong>
  Pin: <%= @box.access.pin if @box.access %> | 
  Barcode: <%= @box.access.barcode if @box.access %>
</p>

<% if @box.status == @constant['BOX_RETURNED'] %>
  <p>
    <strong>Backup Package for Delivery:</strong><br/>
    <% if @selected_backup_package %>
      Current Backed up Package: 
      <%= @selected_backup_package.barcode %>
    <% end %>
    <%= form_tag("assign_backup", method: "post") do %>
  	  <%= select '', :package_id, @unassigned_packages_for_delivery.collect{|p|
	  	  	print_info = p.barcode
	  	  	[print_info, p.id]
  	      }, include_blank: 'No/Cancel Assignment' %>
  	  <%= submit_tag 'Assign Backup' %>
  	  <%= hidden_field_tag :id, @box.id %>
  	<% end %>
  </p>
<% end %>

<p>
  <strong>Permission:</strong>
  Employees: 
  <% if @box.permissions %>
	<% @box.permissions.each do |p| %>
	  <%= p.employee.name %>
	<% end %>
  <% end %>
</p>

<p>
  <strong>Remote open:</strong>
  <%= link_to 'Open', open_box_path(@box), method: :post %>
</p>

<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', locker_path(@box.locker) %>