config/routes.rb
GreenLockers::Application.routes.draw do
  root :to => "pages#index"
  post "api/DoorOpened(.:format)" => "api#DoorOpened"
  post "api/DropOff(.:format)"
  post "api/SyncAccessInfo(.:format)"
  post "api/SyncOperatorInfo(.:format)"
  post "api/SyncAdminInfo(.:format)"
  post "api/BarcodeNotExist(.:format)"
  post "api/BoxIntruded(.:format)"
  
  post "boxes/assign"
  post "boxes/assign_backup"
  post "boxes/reassign"
  post "boxes/reassign_backup"
  post "boxes/delivered"
  post "boxes/picked_up"
  post "boxes/dropped_off"
  post "boxes/received"
  post "boxes/:id/open", to: "boxes#open", as: "open_box"
  
  post "lockers/:id/sync", to: "lockers#sync", as: "sync_locker"
  
  post "employees/set_permissions"
  post "employees/set_privileges"
  
  resources :lockers

  resources :employees

  resources :trackings

  resources :packages

  resources :branches

  resources :boxes

  resources :users
  
  get "logs" => "loggings#index"
  get "logs/box/:id", to: "loggings#box_logs", as: "box_logs"
  get "logs/package/:id", to: "loggings#package_logs", as: "package_logs"
  get "packages/:id/get_available_boxes" => "packages#get_available_boxes"

  

end

app/models/locker.rb
require "net/http"
require "uri"

class Locker < ActiveRecord::Base
  belongs_to :branch
  has_many :boxes
  has_many :packages, :through => :boxes
  has_many :privileges
  has_many :devicelog
  CONSTANT = YAML.load_file("#{Rails.root}/config/constant.yml")
  
  # Create associated boxes after creating the locker
  def init_locker
    box_params = {}
    box_params[:locker_id] = self.id
    30.times do |i|
      box_params[:name] = (i+1).to_s
      box_params[:size] = 1;
      box_params[:status] = 0;
      b = Box.new(box_params)
      if b.save
        b.init_box
      end
    end
    # 8.times do |i|
      # box_params[:name] = 'B'+(i+1).to_s
      # box_params[:size] = 2;
      # box_params[:status] = 0;
      # b = Box.new(box_params)
      # if b.save
        # b.init_box
      # end
    # end
    # 6.times do |i|
      # box_params[:name] = 'C'+(i+1).to_s
      # box_params[:size] = 3;
      # box_params[:status] = 0;
      # b = Box.new(box_params)
      # if b.save
        # b.init_box
      # end
    # end
  end
  
  def enforce_sync
    uri = URI.parse(CONSTANT['PROXY_SERVER_BASE_URL_1'])
    #uri = URI.parse('http://echo.jsontest.com/status/true')

    http = Net::HTTP.new(uri.host, uri.port)
    #request = Net::HTTP::Get.new(uri.request_uri)
    request = Net::HTTP::Post.new(uri.request_uri)
    request.set_form_data({"action" => "EnforceSync", "sDeviceID" => self.name.to_s, "uMillsec" => '6000'})
    #request.basic_auth("username", "password")
    response = http.request(request)
    if response.body
      body = JSON.parse response.body
      if body["status"]
        return true
      end
    end
    return false
  end
  
end

app/controllers/lockers_controller.rb
class LockersController < ApplicationController
  before_action :set_locker, only: [:show, :sync, :edit, :update, :destroy, :init_locker]
  # GET /lockers
  # GET /lockers.json
  def index
    @lockers = Locker.all
  end

  # GET /lockers/1
  # GET /lockers/1.json
  def show 
      u_packages = Package.where("box_id is NULL and (status = 0 OR status = 5) AND status IS NOT NULL").order('updated_at ASC')
      @unassigned_packages = u_packages.select{ |p| 
        if p.preferred_branch_id
          p.preferred_branch_id == @locker.branch_id
        elsif p.user.preferred_branch_id
          p.user.preferred_branch_id == @locker.branch_id
        else
          true == false
        end 
      }
  end
  
  def sync
    respond_to do |format|
      if @locker.enforce_sync
        format.html { redirect_to lockers_path, notice: 'Sync request is sent.' }
      else
        format.html { redirect_to lockers_path, alert: 'Oops. Something went wrong.' }
      end
    end
  end

  # GET /lockers/new
  def new
    @locker = Locker.new
  end

  # GET /lockers/1/edit
  def edit
  end

  # POST /lockers
  # POST /lockers.json
  def create
    @locker = Locker.new(locker_params)

    respond_to do |format|
      if @locker.save
        @locker.init_locker
        format.html { redirect_to @locker, notice: 'Locker was successfully created.' }
        format.json { render action: 'show', status: :created, location: @locker }
      else
        format.html { render action: 'new' }
        format.json { render json: @locker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lockers/1
  # PATCH/PUT /lockers/1.json
  def update
    respond_to do |format|
      if @locker.update(locker_params)
        format.html { redirect_to @locker, notice: 'Locker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @locker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lockers/1
  # DELETE /lockers/1.json
  def destroy
    @locker.boxes.each do |b|
      b.destroy
      b.access.destroy
    end
    @locker.destroy
    respond_to do |format|
      format.html { redirect_to lockers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locker
      @locker = Locker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def locker_params
      params.require(:locker).permit(:branch_id, :name)
    end

end

app/helpers/lockers_helper.rb
module LockersHelper
end

app/views/lockers/_form.html.erb
<%= form_for(@locker) do |f| %>
  <% if @locker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@locker.errors.count, "error") %> prohibited this locker from being saved:</h2>

      <ul>
      <% @locker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :branch_id %><br>
    <%= f.collection_select :branch_id, Branch.order(:city),:id,:name, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lockers/_formassign.html.erb
  <%= form_tag("/boxes/assign", method: "post") do %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel-assign">Assign Package</h4>
      </div>
      <div class="modal-body">
		<h5>Package Selected:</h5> <input type="text" class='form-control' id='package-info' placeholder="None" disabled>
		<input type="hidden" class='form-control' id='package-id' name="package_id">
		<input type="hidden" class='form-control' id='package-id-origin' name="origin_package_id">
		<input type="hidden" class='form-control' id='box-id' name="id">
		<br/>
		<h5>Options Available:</h5>
		<ul class="nav nav-tabs">
		  <li class="active"><a href="#delivery" data-toggle="tab">Delivery</a></li>
		  <li><a href="#dropoff" data-toggle="tab">Drop off</a></li>
		</ul>
		<div class="tab-content">
		  <div class="tab-pane active tablescroll" id="delivery">
			<table class='table table-center'>
			  <thead class='scroll'>
			  	<tr>
			      <th>Barcode</th>
  				  <th>User</th>
  				  <th>Size</th>
  				  <th>Datetime</th>
			      <th></th>
			    </tr>
			  </thead>
			  <tbody class='scroll'>
		  	  <% @unassigned_packages.select{|u| u.status==@constant['PACKAGE_WAITING_FOR_DELIVERY']}.each do |p| %>
		  	  	<tr class='row-for-package' id='row-for-<%= p.id %>'>
		  	  	  <td><%= p.barcode %></td>
		  	  	  <td><%= p.user.user_name %></td>
		  	  	  <td><%= p.print_size %></td>
		  	  	  <td><%= p.created_at.to_s %></td>
		  	  	  <td class='cell-for-button'>
		  	  	  	<%= content_tag(:span, content_tag(:span, '', :class => 'glyphicon glyphicon-ok') + ' Assign', :pid => p.id, :pinfo => 'Package: ' + p.barcode + '    User: ' + p.user.user_name + '    Size: ' + p.print_size + '    Status: ' + p.print_status, :class => 'btn btn-default btn-xs assign btn-success')%>
		  	  	  	<%= content_tag(:span, content_tag(:span, '', :class => 'glyphicon glyphicon-remove') + ' Cancel', :pid => p.id, :pinfo => 'Package: ' + p.barcode + '    User: ' + p.user.user_name + '    Size: ' + p.print_size + '    Status: ' + p.print_status, :class => 'btn btn-default btn-xs cancel btn-danger')%>
		  	  	  </td>
		  	  	</tr>
		  	  <% end %>
			  </tbody>
			</table>
		  </div>
		  <div class="tab-pane tablescroll" id="dropoff">
			<table class='table table-center'>
			  <thead class='scroll'>
			  	<tr>
			      <th>Barcode</th>
  				  <th>User</th>
  				  <th>Size</th>
  				  <th>Datetime</th>
			      <th></th>
			    </tr>
			  </thead>
			  <tbody class='scroll'>
		      <% @unassigned_packages.select{|u| u.status==@constant['PACKAGE_WAITING_FOR_DROP_OFF']}.each do |p| %>
		  	  	<tr class='row-for-package' id='row-for-<%= p.id %>'>
		  	  	  <td><%= p.barcode %></td>
		  	  	  <td><%= p.user.user_name %></td>
		  	  	  <td><%= p.print_size %></td>
		  	  	  <td><%= p.created_at.to_s %></td>
		  	  	  <td class='cell-for-button'>
		  	  	  	<%= content_tag(:span, content_tag(:span, '', :class => 'glyphicon glyphicon-ok') + ' Assign', :pid => p.id, :pinfo => 'Package: ' + p.barcode + '    User: ' + p.user.user_name + '    Size: ' + p.print_size + '    Status: ' + p.print_status, :class => 'btn btn-default btn-xs assign btn-success')%>
		  	  	  	<%= content_tag(:span, content_tag(:span, '', :class => 'glyphicon glyphicon-remove') + ' Cancel', :pid => p.id, :pinfo => 'Package: ' + p.barcode + '    User: ' + p.user.user_name + '    Size: ' + p.print_size + '    Status: ' + p.print_status, :class => 'btn btn-default btn-xs cancel btn-danger')%>
		  	  	  </td>
		  	  	</tr>
		  	  <% end %>					  	
			  </tbody>
			</table>
		  </div>
		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="close-button" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" id="assign-button" disabled>Assign</button>
      </div>
  <% end %>

app/views/lockers/_formbackup.html.erb
  <%= form_tag("/boxes/assign_backup", method: "post") do %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Assign Backup Package</h4>
      </div>
      <div class="modal-body">
		<h5>Package Selected:</h5> <input type="text" class='form-control' id='backup-package-info' placeholder="None" disabled>
		<input type="hidden" class='form-control' id='backup-package-id' name="package_id">
		<input type="hidden" class='form-control' id='backup-package-id-origin' name="origin_package_id">
		<input type="hidden" class='form-control' id='backup-box-id' name="id">
		<br/>
		<h5>Options Available:</h5>
  		<div class="tablescroll">
			<table class='table table-center'>
			  <thead class='scroll'>
			  	<tr>
			      <th>Barcode</th>
  				  <th>User</th>
  				  <th>Size</th>
  				  <th>Datetime</th>
			      <th></th>
			    </tr>
			  </thead>
			  <tbody class='scroll'>
		  	  <% @unassigned_packages.select{|u| u.status==@constant['PACKAGE_WAITING_FOR_DELIVERY']}.each do |p| %>
		  	  	<tr class='row-for-backup-package' id='row-for-backup-<%= p.id %>'>
		  	  	  <td><%= p.barcode %></td>
		  	  	  <td><%= p.user.user_name %></td>
		  	  	  <td><%= p.print_size %></td>
		  	  	  <td><%= p.created_at.to_s %></td>
		  	  	  <td class='cell-for-button'>
		  	  	  	<%= content_tag(:span, content_tag(:span, '', :class => 'glyphicon glyphicon-ok') + ' Assign', :pid => p.id, :pinfo => 'Package: ' + p.barcode + '    User: ' + p.user.user_name + '    Size: ' + p.print_size + '    Status: ' + p.print_status, :class => 'btn btn-default btn-xs backup-assign btn-success')%>
		  	  	  	<%= content_tag(:span, content_tag(:span, '', :class => 'glyphicon glyphicon-remove') + ' Cancel', :pid => p.id, :pinfo => 'Package: ' + p.barcode + '    User: ' + p.user.user_name + '    Size: ' + p.print_size + '    Status: ' + p.print_status, :class => 'btn btn-default btn-xs backup-cancel btn-danger')%>
		  	  	  </td>
		  	  	</tr>
		  	  <% end %>
			  </tbody>
			</table>
		</div>
	  </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="backup-close-button" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" id="backup-assign-button" disabled>Assign</button>
      </div>
		
		
  <% end %>

app/views/lockers/_tablelog.html.erb
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Logs for Box <span id='log-box-id'></span></h4>
  </div>
  <div class="modal-body">
  	<div class="tablescroll-long">
      	<table class='table'>
		  <thead class='scroll'>
		  	<tr>
		  	  <th>Description</th>
		  	  <th>Package</th>
		  	  <th>Time</th>
		  	  <th>Access</th>
		  	</tr>
		  </thead>
		  <tbody class='scroll logs'>
	  	  
		  </tbody>
		</table>
	</div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" id="close-button" data-dismiss="modal">Close</button>
  </div>

app/views/lockers/edit.html.erb
<h4>Edit Locker</h4>

<%= render 'form' %>

<%= link_to 'Show', @locker %> |
<%= link_to 'Back', lockers_path %>

app/views/lockers/index.html.erb
<h4>Lockers</h4>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>Branch</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lockers.each do |locker| %>
      <tr>
        <td><%= locker.branch.name %></td>
        <td><%= locker.name %></td>
        <td><%= link_to 'Manage Boxes', locker %></td>
        <td><%= link_to 'Sync', sync_locker_path(locker), method: :post %></td>
        <td><%= link_to 'Edit', edit_locker_path(locker) %></td>
        <td><%= link_to 'Destroy', locker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Locker', new_locker_path %>

app/views/lockers/new.html.erb
<h4>Create New Locker</h4>

<%= render 'form' %>

<%= link_to 'Back', lockers_path %>

app/views/lockers/show.html.erb
<div class="alert alert-success alert-dismissable notice-div">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <p><%= notice %></p>
</div>

<h4>Boxes</h4>

<b>Branch:</b> <%= @locker.branch.name %><br/> 
<b>Locker:</b> <%= @locker.name %> <br/>
<%= link_to 'Back to Lockers', lockers_path %>

<table class='table table-center'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Status</th>
      <th>Package</th>
      <th>Backup</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locker.boxes.each do |box| %>
      <tr class='
        <% if box.print_status == 'Delivering' or box.print_status == 'Delivered' or box.print_status == 'Returning' or box.print_status == 'Returned' %>
      	  <%= 'alert alert-success' %>
      	<% elsif box.print_status == 'Error' %>
      	  <%= 'alert alert-danger' %>
      	<% end %>
      	'>
        <td><%= box.name %></td>
        <td><%= box.print_size %></td>
        <td><%= box.print_status %></td>
        <td><% if box.package %>
        	  <%= box.package.barcode %>
        	<% else %>
        	  <%=link_to content_tag(:span, '', :class => 'glyphicon glyphicon-paperclip') + ' Assign',  '', "data-toggle"=>"modal", "data-target"=>'#myModal-assign', "box-id"=>box.id.to_s, :class => 'btn btn-default btn-xs modal-trigger' %>
        	<% end %>
        </td>
        <td><% if box.backup_package %>
        	  <%= box.backup_package.barcode %>
        	<% elsif box.print_status != 'Returned' %>
        	  <%= '-' %>
        	<% else %>
        	  <%=link_to content_tag(:span, '', :class => 'glyphicon glyphicon-paperclip') + ' Assign',  '', "data-toggle"=>"modal", "data-target"=>'#myModal-backup', "box-id"=>box.id.to_s, :class => 'btn btn-default btn-xs modal-backup-trigger' %>
        	<% end %>
        </td>
        <td>
	        <%=link_to content_tag(:span, '', :class => 'glyphicon glyphicon-wrench') + ' Manage', box, :class => 'btn btn-default btn-xs' %> 
	        <%=link_to content_tag(:span, '', :class => 'glyphicon glyphicon-list-alt') + ' Logs', '', "data-toggle"=>"modal", "data-target"=>'#myModal-logs', "box-id"=>box.id.to_s, :class => 'btn btn-default btn-xs modal-box-logs-trigger' %> 
	        <%=link_to content_tag(:span, '', :class => 'glyphicon glyphicon-pencil') + ' Edit', edit_box_path(box), :class => 'btn btn-default btn-xs' %> 
	        <%=link_to content_tag(:span, '', :class => 'glyphicon glyphicon-trash') + ' Delete', box, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-default btn-xs' %>
	    </td>
      </tr>
    <% end %>
  </tbody>
</table>

	<div class="modal fade modal-assign" id="myModal-assign" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <%= render 'formassign' %>
	    </div>
	  </div>
	</div>
	
    <div class="modal fade modal-backup" id="myModal-backup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
		  <%= render 'formbackup'%>
	    </div>
	  </div>
	</div>
	
	<div class="modal fade modal-backup" id="myModal-logs" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <%= render 'tablelog' %>
		</div>
	  </div>
	</div>
<br>

<%= link_to 'New Box', new_box_path %>